export const OTP_CODE_STATUS = {
  AVAILABLE: 'AVAILABLE',
  USED: 'USED',
} as const;

export enum CHARGE_TYPE {
  PERCENTAGE = 'PERCENTAGE',
  FIXED = 'FIXED',
}

export enum ENTRY_POINT_TYPE {
  PERCENTAGE = 'PERCENTAGE',
  FIXED = 'FIXED',
}

export enum PARTNERSHIP_TYPE {
  JOINT_VENTURE = 'JOINT_VENTURE',
  STRATEGIC_ALLIANCE = 'STRATEGIC_ALLIANCE',
  FRANCHISING = 'FRANCHISING',
  EQUITY_PARTNERSHIP = 'EQUITY_PARTNERSHIP',
  LICENSING = 'LICENSING',
}
