export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  SERVICE_PROVIDER_ADMIN = 'SERVICE_PROVIDER_ADMIN',
  COOPERATIVE_ADMIN = 'COOPERATIVE_ADMIN',
  USER = 'USER',
  SAVING_INSTITUTION_ADMIN = 'SAVING_INSTITUTION_ADMIN',
}
